import React from 'react';
import {
  CheckCircle2,
  XCircle,
  Printer,
  Download,
  Copy,
  Check,
  X,
  ExternalLink,
  Clock,
} from 'lucide-react';
import { CYKResult } from '../types/cyk.ts';
import { sound } from '../utils/sound.ts';
import { exportJSON, exportCSV, generateStandaloneReportHTML } from '../utils/export.ts';

interface AnswerPopupProps {
  result: CYKResult | null;
  grammarText: string;
  isOpen: boolean;
  onClose: () => void;
  onViewTable: () => void;
  onPrint: () => void;
}

export const AnswerPopup: React.FC<AnswerPopupProps> = ({
  result,
  grammarText,
  isOpen,
  onClose,
  onViewTable,
  onPrint,
}) => {
  const [copied, setCopied] = React.useState(false);

  if (!isOpen || !result) return null;

  const handleCopyJSON = () => {
    sound.play('click');
    navigator.clipboard.writeText(JSON.stringify(result, null, 2));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadReport = () => {
    sound.play('click');
    const html = generateStandaloneReportHTML(result, grammarText);
    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `cyk-report-${result.input}-${Date.now()}.html`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div
      role="dialog"
      aria-modal="true"
      className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/65 backdrop-blur-md animate-in fade-in duration-200"
    >
      <div className="relative w-full max-w-xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl shadow-2xl overflow-hidden flex flex-col">
        {/* Top Status Header */}
        <div
          className={`px-6 py-6 text-center border-b ${
            result.accepted
              ? 'bg-emerald-500/10 dark:bg-emerald-950/30 border-emerald-200 dark:border-emerald-900/60'
              : 'bg-rose-500/10 dark:bg-rose-950/30 border-rose-200 dark:border-rose-900/60'
          }`}
        >
          <div className="flex justify-end absolute top-3 right-3">
            <button
              onClick={() => {
                sound.play('click');
                onClose();
              }}
              className="p-1.5 text-slate-400 hover:text-slate-700 dark:hover:text-slate-200 rounded-lg hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors"
              aria-label="Close modal"
            >
              <X className="w-5 h-5" />
            </button>
          </div>

          <div className="mx-auto flex items-center justify-center mb-2">
            {result.accepted ? (
              <div className="w-14 h-14 rounded-full bg-emerald-100 dark:bg-emerald-900/60 text-emerald-600 dark:text-emerald-400 flex items-center justify-center shadow-inner">
                <CheckCircle2 className="w-8 h-8" />
              </div>
            ) : (
              <div className="w-14 h-14 rounded-full bg-rose-100 dark:bg-rose-900/60 text-rose-600 dark:text-rose-400 flex items-center justify-center shadow-inner">
                <XCircle className="w-8 h-8" />
              </div>
            )}
          </div>

          <h2
            className={`text-xl font-extrabold tracking-tight ${
              result.accepted
                ? 'text-emerald-700 dark:text-emerald-300'
                : 'text-rose-700 dark:text-rose-300'
            }`}
          >
            {result.accepted ? '✓ STRING ACCEPTED' : '✕ STRING REJECTED'}
          </h2>

          <p className="text-xs sm:text-sm text-slate-600 dark:text-slate-400 mt-1 max-w-md mx-auto">
            {result.accepted
              ? `The Chomsky Normal Form grammar successfully derives the string "${result.input}". Start symbol '${result.startSymbol}' was found in root cell T[0][${result.length - 1}].`
              : `The string "${result.input}" cannot be generated by this grammar. Start symbol '${result.startSymbol}' is absent from root cell T[0][${result.length - 1}].`}
          </p>
        </div>

        {/* Diagnostic Metadata Grid */}
        <div className="p-6 space-y-4">
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-2.5 text-center">
            <div className="p-3 rounded-xl bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800">
              <span className="text-[10px] uppercase font-semibold text-slate-400">
                Input String
              </span>
              <div className="font-mono font-bold text-sm text-slate-900 dark:text-slate-100 truncate mt-0.5">
                "{result.input}"
              </div>
            </div>

            <div className="p-3 rounded-xl bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800">
              <span className="text-[10px] uppercase font-semibold text-slate-400">
                Start Symbol
              </span>
              <div className="font-mono font-bold text-sm text-indigo-600 dark:text-indigo-400 mt-0.5">
                {result.startSymbol}
              </div>
            </div>

            <div className="p-3 rounded-xl bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800">
              <span className="text-[10px] uppercase font-semibold text-slate-400">
                Root Cell Set
              </span>
              <div className="font-mono font-bold text-sm text-slate-900 dark:text-slate-100 mt-0.5">
                {result.rootNonTerminals.length > 0
                  ? `{${result.rootNonTerminals.join(',')}}`
                  : '∅'}
              </div>
            </div>

            <div className="p-3 rounded-xl bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800">
              <span className="text-[10px] uppercase font-semibold text-slate-400">
                Execution Time
              </span>
              <div className="font-mono font-bold text-sm text-slate-900 dark:text-slate-100 mt-0.5">
                {result.executionTimeMs} ms
              </div>
            </div>
          </div>

          {/* Algorithm Badge */}
          <div className="flex items-center justify-between px-3.5 py-2.5 rounded-lg bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 text-xs">
            <div className="flex items-center gap-2 text-slate-600 dark:text-slate-400">
              <Clock className="w-3.5 h-3.5 text-indigo-500" />
              <span>Algorithm: <strong>Cocke–Younger–Kasami (CYK)</strong></span>
            </div>
            <div className="text-slate-500 font-mono text-[11px]">
              O(n³·|G|) Complexity
            </div>
          </div>

          {/* Action Button Row */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 pt-2">
            {/* Print Result */}
            <button
              onClick={() => {
                sound.play('click');
                onPrint();
              }}
              className="px-3 py-2 text-xs font-semibold text-slate-700 dark:text-slate-200 bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 rounded-lg transition-colors flex items-center justify-center gap-1.5"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print Report</span>
            </button>

            {/* Download Report HTML */}
            <button
              onClick={handleDownloadReport}
              className="px-3 py-2 text-xs font-semibold text-slate-700 dark:text-slate-200 bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 rounded-lg transition-colors flex items-center justify-center gap-1.5"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Download Report</span>
            </button>

            {/* Copy JSON */}
            <button
              onClick={handleCopyJSON}
              className="px-3 py-2 text-xs font-semibold text-slate-700 dark:text-slate-200 bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 rounded-lg transition-colors flex items-center justify-center gap-1.5"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-500" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? 'Copied!' : 'Copy JSON'}</span>
            </button>

            {/* View Table */}
            <button
              onClick={() => {
                sound.play('click');
                onViewTable();
              }}
              className="px-3 py-2 text-xs font-semibold text-indigo-600 dark:text-indigo-400 bg-indigo-50 dark:bg-indigo-950/80 hover:bg-indigo-100 dark:hover:bg-indigo-900/60 rounded-lg transition-colors flex items-center justify-center gap-1.5"
            >
              <ExternalLink className="w-3.5 h-3.5" />
              <span>View Table</span>
            </button>
          </div>
        </div>

        {/* Footer */}
        <div className="px-6 py-3 border-t border-slate-200 dark:border-slate-800 bg-slate-50/50 dark:bg-slate-950/50 flex justify-end">
          <button
            onClick={() => {
              sound.play('click');
              onClose();
            }}
            className="px-5 py-2 text-xs font-bold text-white bg-slate-900 dark:bg-slate-100 dark:text-slate-900 hover:bg-slate-800 dark:hover:bg-slate-200 rounded-lg transition-colors"
          >
            Close Result
          </button>
        </div>
      </div>
    </div>
  );
};
