import React from 'react';
import { CYKResult, ValidationResult } from '../types/cyk.ts';

interface PrintReportProps {
  result: CYKResult | null;
  grammarText: string;
  validation: ValidationResult;
}

export const PrintReport: React.FC<PrintReportProps> = ({
  result,
  grammarText,
  validation,
}) => {
  if (!result) return null;

  const n = result.length;
  const chars = result.input.split('');

  return (
    <div className="hidden print:block p-8 bg-white text-black font-sans leading-relaxed">
      {/* Title & Header */}
      <div className="border-b-2 border-slate-900 pb-4 mb-6">
        <h1 className="text-2xl font-bold tracking-tight text-black">
          CYK Parser Studio · Parsing Report
        </h1>
        <p className="text-xs text-slate-600 mt-1">
          Cocke–Younger–Kasami Dynamic Programming Algorithm Verification · Generated on {new Date().toLocaleString()}
        </p>
      </div>

      {/* Outcome Banner */}
      <div
        className={`p-4 rounded border mb-6 ${
          result.accepted ? 'bg-emerald-50 border-emerald-500' : 'bg-rose-50 border-rose-500'
        }`}
      >
        <div className="text-lg font-bold">
          {result.accepted ? '✓ STRING ACCEPTED' : '✕ STRING REJECTED'}
        </div>
        <p className="text-sm mt-1">
          {result.accepted
            ? `Input string "${result.input}" belongs to the language L(G) generated by this grammar.`
            : `Input string "${result.input}" does NOT belong to the language L(G).`}
        </p>
      </div>

      {/* Metadata Overview */}
      <div className="grid grid-cols-4 gap-4 p-4 border border-slate-300 rounded mb-6 text-sm">
        <div>
          <span className="text-xs text-slate-500 uppercase">Input String (w)</span>
          <div className="font-mono font-bold mt-0.5">"{result.input}"</div>
        </div>
        <div>
          <span className="text-xs text-slate-500 uppercase">Start Symbol</span>
          <div className="font-mono font-bold mt-0.5">{result.startSymbol}</div>
        </div>
        <div>
          <span className="text-xs text-slate-500 uppercase">Execution Time</span>
          <div className="font-mono font-bold mt-0.5">{result.executionTimeMs} ms</div>
        </div>
        <div>
          <span className="text-xs text-slate-500 uppercase">Root Cell T[0][{n - 1}]</span>
          <div className="font-mono font-bold mt-0.5">
            {result.rootNonTerminals.length > 0 ? `{${result.rootNonTerminals.join(', ')}}` : '∅'}
          </div>
        </div>
      </div>

      {/* Grammar Section */}
      <div className="border border-slate-300 rounded p-4 mb-6">
        <h2 className="text-sm font-bold uppercase tracking-wide mb-2">
          1. Chomsky Normal Form (CNF) Grammar
        </h2>
        <pre className="font-mono text-xs bg-slate-50 p-3 rounded border border-slate-200 whitespace-pre-wrap">
          {grammarText}
        </pre>
        <div className="text-xs text-slate-600 mt-2">
          Validation: <strong>{validation.valid ? 'Valid CNF' : 'Invalid'}</strong> · Total Rules: {validation.totalProductions} · Non-Terminals: {validation.nonTerminals.join(', ')}
        </div>
      </div>

      {/* Triangular Table Section */}
      <div className="border border-slate-300 rounded p-4 mb-6">
        <h2 className="text-sm font-bold uppercase tracking-wide mb-2">
          2. CYK Triangular Dynamic Programming Table
        </h2>
        <div className="text-xs text-slate-500 mb-3">
          Row <strong>len = l</strong> represents derivations for all substrings of length <strong>l</strong>.
        </div>

        <div className="flex flex-col items-center gap-2">
          {Array.from({ length: n }, (_, rowIdx) => {
            const len = n - rowIdx;
            const cellCount = n - len + 1;

            return (
              <div key={len} className="flex items-center gap-2">
                <span className="w-14 text-right text-xs font-mono text-slate-500">
                  len={len}
                </span>
                <div className="flex gap-2">
                  {Array.from({ length: cellCount }, (_, i) => {
                    const j = i + len - 1;
                    const cell = result.table[i][j];
                    const isRoot = len === n;

                    return (
                      <div
                        key={`${i}-${j}`}
                        className={`w-20 p-1.5 border rounded text-center text-xs font-mono ${
                          isRoot
                            ? result.accepted
                              ? 'bg-emerald-50 border-emerald-500 font-bold'
                              : 'bg-rose-50 border-rose-500 font-bold'
                            : 'bg-slate-50 border-slate-300'
                        }`}
                      >
                        <div className="text-[9px] text-slate-500">[{i},{j}]</div>
                        <div className="font-bold my-1">
                          {cell.nonTerminals.length > 0 ? `{${cell.nonTerminals.join(',')}}` : '∅'}
                        </div>
                        <div className="text-[9px] text-slate-600 truncate">"{cell.substring}"</div>
                      </div>
                    );
                  })}
                </div>
              </div>
            );
          })}

          <div className="flex items-center gap-2 pt-2 border-t border-slate-300 mt-2">
            <span className="w-14 text-right text-xs font-mono font-bold text-slate-700">
              input:
            </span>
            <div className="flex gap-2">
              {chars.map((ch, idx) => (
                <div key={idx} className="w-20 py-1 text-center font-mono font-bold text-xs bg-slate-100 border border-slate-300 rounded">
                  '{ch}' <span className="text-[10px] text-slate-500">({idx})</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>

      {/* Complexity and Theoretical Basis */}
      <div className="border border-slate-300 rounded p-4 text-xs text-slate-700">
        <h2 className="font-bold uppercase tracking-wide mb-1 text-black">
          3. Complexity Analysis & Invariants
        </h2>
        <ul className="list-disc list-inside space-y-1">
          <li><strong>Time Complexity:</strong> O(n³ · |G|) where n = {n} and grammar size |G| = {result.grammarSize}. For fixed grammar: O(n³).</li>
          <li><strong>Space Complexity:</strong> O(n² · |N|) where non-terminal count |N| = {result.nonTerminalsCount}.</li>
          <li><strong>Dynamic Programming Equation:</strong> T[i][j] = ⋃ (k = i to j-1) {'{ A | A → BC, B ∈ T[i][k], C ∈ T[k+1][j] }'}.</li>
          <li><strong>Decision Rule:</strong> Input w is accepted if and only if StartSymbol ({result.startSymbol}) ∈ T[0][{n - 1}].</li>
        </ul>
      </div>
    </div>
  );
};
